config/routes.rb
Rails.application.routes.draw do
  get '/privacy_policy', to: 'privacy_policy#show'
  get '/auth/facebook', as: 'facebook_login'
  match '/auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  root 'users#show'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :users, only: [:show, :create]
  resources :leagues, only: [:show, :create] do
    resources :teams, only: [:index]
  end
  get '/start', to: 'start#show'
  resources :weeks, only: [:show]
  resources :contestants, only: [:show]
  get '/league_search', to: 'league_search#show'
  resources :team_members, only: [:create]
  resources :teams, only: [:create, :destroy] do
    resources :draft_picks, only: [:index]
    put '/draft_picks', to: 'draft_picks#update'
  end
  namespace :admin do
    resources :weekly_contestants, only: [:create]
    resources :team_contestants, only: [:create]
    resources :seasons, only: [:create, :index, :show, :update]
    resources :contestants, only: [:create]
    resources :weeks, only: [:create]
    resources :actions, only: [:create]
  end

  namespace :api do
    namespace :v1 do
      namespace :contestants do
        get ':id/weekly_points', to: 'points#show'
      end
      namespace :leagues do
        get ':id/team_points', to: 'team_points#index'
        get ':id/comments', to: 'comments#index'
        post ':id/comments', to: 'comments#create'
      end
    end
  end
end

app/models/league.rb
class League < ApplicationRecord
  belongs_to :season
  has_many :teams, dependent: :destroy
  has_many :comments, dependent: :destroy

  def team_of_user(user)
    teams.select("teams.*")
          .joins(:team_members)
          .find_by("team_members.user_id = ?", user.id)
  end

  def owner_of(contestant)
    teams.joins(:contestants).find_by("contestants.id = ?", contestant.id)
  end

  def team_points
    teams.map do |team|
      points = []
      10.times do |n|
        week = season.weeks.find_by(week_number: n+1)
        points << ((team.week_points(week) if week) || 0)
      end
      {name: team.name, points: points}
    end
  end
end

app/controllers/api/v1/leagues/comments_controller.rb
class Api::V1::Leagues::CommentsController < ApplicationController
  def index
    comments = League.find(params[:id]).comments
    comments_with_user_names = comments.map {|comment| {message: comment.message, user: User.find(comment.user_id).name, date: comment.created_at.to_formatted_s(:long_ordinal)}}
    render json: comments_with_user_names
  end

  def create
    League.find(params[:id]).comments.create(comment_params.merge({user: current_user}))
  end

  private

  def comment_params
    params.require(:comment).permit(:message)
  end

end

app/controllers/api/v1/leagues/team_points_controller.rb
class Api::V1::Leagues::TeamPointsController < ApplicationController
  def index
    render json: League.find(params[:id]).team_points
  end
end

app/controllers/leagues_controller.rb
class LeaguesController < ApplicationController
  def show
    @league = (League.find(params[:id]) if params[:id]) || current_user.leagues.first
    @comment = Comment.new(league: @league)
  end

  def create
    @league = League.create!(league_params)
    @team = current_user.teams.create!(name: params[:league][:team], league: @league)
    flash[:notice] = "You've created league #{@league.name} and team #{@team.name}!"
    redirect_to @league
  end

  private

  def league_params
    name = params.require(:league).permit(:name)
    name[:name].strip!
    name.merge(season_id: current_season.id)
  end
end

app/views/leagues/_after_draft_picks.html.erb
<div class="text-center">
<h3>Team <%= @league.team_of_user(current_user).name.possessive %> Draft Picks </h3><br>
<h5>This season's draft takes place on <%= current_season.draft_date.to_formatted_s(:long_ordinal) %>. Visit the draft room to edit your picks. </h5><br>
<%= link_to "Edit Draft Picks", team_draft_picks_path(@league.team_of_user(current_user)), class: "btn btn-primary btn-lg" %>
</div><br>

<div class="draft-picks">
<!-- <div class="row"> -->
<ol class="draft-rank-list">
  <% @league.team_of_user(current_user).draft_picks.order(:rank).each do |pick| %>
  <!-- <div class="col-md-4">
  <div class=""> -->
  <li>
  <div>
    <div class=" d-flex ">
        <div class="draft-img-container">
          <img class = "circular-cont-headshots" src="<%= pick.contestant.headshot %>" alt="contestant-headshot">
        </div>
      <span class ="cont-name align-middle"> <%= link_to pick.contestant.name, pick.contestant %></span>
    </div>
  </div>
</li>
  <!-- </div>
</div> -->
  <% end %>
</ol>
<!-- </div> -->
</div>

app/views/leagues/_info.html.erb
<table class="table">
  <thead class ="card-header">
    <tr>
      <th scope="col">Team Name</th>
      <td scope="col">Members</td>
    </tr>
  </thead>
  <tbody>
    <% @league.teams.each do |team| %>
      <tr>
        <th scope="row"><%= team.name %></th>
        <td><% team.users.each do |user| %>
            <%= user.name %><br>
            <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/leagues/_manage_league.html.erb
<% unless current_user.leagues.include?(@league) %>
<h4 class = "text-center">Join or Create Team! </h4>
<% end %>
<h5 class = "text-center">There are up to 4 teams allowed per league, but unlimited players on each team.</h5>
<br>
<div class="card">
<div>
<table class="table">
  <thead class ="card-header">
    <tr>
      <th scope="col"></th>
      <th scope="col">Team Name</th>
      <td scope="col">Members</td>
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody>
    <% @league.teams.each do |team| %>
      <tr>
        <th scope="row"></th>
        <th scope="row"><%= team.name %></th>
        <td><% team.users.each do |user| %>
            <%= user.name %><br>
            <% end %>
        </td>
        <% if current_user.teams.include?(team) %>
          <td><%= link_to "Delete Team", team_path(team), method: :delete, class: "btn btn-red btn-sm" %></td>
        <% elsif @league.team_of_user(current_user) == nil %>
          <td><%= link_to "Join", team_members_path(team_id: team.id, user_id: current_user.id), method: :post, class: "btn btn-primary" %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
<% if @league.teams.count < 4 && @league.team_of_user(current_user) == nil %>
<button class="btn btn-primary btn-no-margin" type="button" data-toggle="collapse" data-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">
  Create a New Team
</button>
<% end %>
<div class="collapse" id="collapseExample">
  <div class="card card-body text-center">
    <%= form_for(:team, url: teams_path) do |f| %>
      <%= f.hidden_field :league_id, :value => @league.id %>
      <%= f.label :team_name, "Team Name" %>
      <%= f.text_field :team_name %>
      <%= f.submit 'Create', :class =>"btn btn-primary"%>
    <% end %>
  </div>
</div>



</div>

app/views/leagues/_pre_draft_picks.html.erb
<div class="jumbotron text-center">
  <h1 class="display-4">The draft for <%= current_season.first_name %>'s season takes place on <%= current_season.draft_date.to_formatted_s(:long_ordinal)  %></h1>
<br>
<h3 class="">Visit the draft room to set rankings for team <%= @league.team_of_user(current_user).name %>!</h3>
  <p class="">(It's autodraft, picks must be in before <%= current_season.draft_date.to_formatted_s(:long_ordinal)  %>)</p>
  <div class="text-center">

  <img class = "big-square-headshot" src="<%= current_season.headshot %>" alt="contestant-headshot">
</div>

  <% current_season.contestants.all[0..15].each do |contestant| %>
  <div class="circle-img-container">

  <span class = "text-center"><img class = "circular-cont-headshots" src="<%= contestant.headshot %>" alt="contestant-headshot">
  </div>
  <% end %>
  <hr class="my-4">
  <p class="lead">
    <%= link_to "Draft Room", team_draft_picks_path(league.team_of_user(current_user)), class: "btn btn-primary btn-lg"%>
  </p>
</div>

app/views/leagues/_user_without_team.html.erb
<h4 class = "text-center">Join or Create Team! </h4>
<div class="card">
<div>
<table class="table">
  <thead class ="card-header">
    <tr>
      <th scope="col"></th>
      <th scope="col">Team Name</th>
      <td scope="col">Members</td>
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody>
    <% @league.teams.each do |team| %>
      <tr>
        <th scope="row"></th>
        <th scope="row"><%= team.name %></th>
        <td><% team.users.each do |user| %>
            <%= user.name %><br>
            <% end %>
        </td>
        <td><%= link_to "Join", team_members_path(team_id: team.id, user_id: current_user.id), method: :post, class: "btn btn-primary" %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
<% if @league.teams.count < 4 %>
<button class="btn btn-primary btn-no-margin" type="button" data-toggle="collapse" data-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">
  Create a New Team
</button>
<% else %>
  <p class = "card-header">Only 4 teams are allowed per league, but teams can have as many members as you want.</p>
<% end %>
<div class="collapse" id="collapseExample">
  <div class="card card-body">
    <%= form_for(:team, url: teams_path) do |f| %>
      <%= f.hidden_field :league_id, :value => @league.id %>
      <%= f.label :team_name, "Team Name" %>
      <%= f.text_field :team_name %>
      <%= f.submit 'Create', :class =>"btn btn-primary"%>
    <% end %>
  </div>
</div>



</div>

app/views/leagues/show.html.erb
<div class="league-show">
<%= tag :div, class: "league_information", data: {id: @league.id} %>

<%= render :partial => "users/user_profile_navbar" %>
<% if @league.team_of_user(current_user) == nil %>
  <%= render :partial => "manage_league", locals: {league: @league} %>
<% elsif @league.team_of_user(current_user).contestants.empty? && !@league.team_of_user(current_user).has_drafted? %>
  <%= render :partial => "pre_draft_picks", locals: {league: @league} %>
<% elsif @league.team_of_user(current_user).contestants.empty? %>
  <%= render :partial => "after_draft_picks", locals: {league: @league} %>
<% else %>
<ul class="nav nav-fill nav-pills" role="tablist">
  <li class="nav-item">
    <a class="nav-link active" data-toggle="tab" href="#league-<%= @league.id %>-league" role="tab">League Overview</a>
  </li>
    <li class="nav-item">
      <a class="nav-link" data-toggle="tab" href="#league-<%= @league.id %>-team" role="tab">League Details</a>
    </li>

</ul>

<!-- Tab panes -->
<div class="tab-content">
  <div class="tab-pane" id="league-<%= @league.id %>-team" role="tabpanel">
    <% @league.teams.each do |team| %>
      <div class="card">
        <div class="card-header">
          <h4 class = text-center>Team <%= team.name %></h4>
        </div>
        <div class="card-body">
          <table class="table table-responsive roster table-sm">
            <thead>
              <tr>
              <p class ="text-center">Week</p>
              </tr>
              <tr>
                <th>Players</th>
                <% 10.times do |n| %>
                <th class = "text-center"><%= n + 1 %></th>
                <% end %>
                <th class = "text-center">Season Total</th>
              </tr>
            </thead>
            <tbody>
              <% team.contestants.each do |contestant| %>
              <tr class= <%= "eliminated-contestant" if contestant.eliminated?%> >
                <td style="width:20%" class="text-left">
                  <div class="d-flex ">
                  <span class="circle-img-container-table">
                    <img class = "circular-cont-headshots" src="<%= contestant.headshot %>" alt="contestant-headshot">
                  </span>
                  <span class="align-self-center" >&nbsp<%= contestant.name %></span>
              </div>
              </td>
              <% 10.times do |n| %>

                <td class = "text-center"><p><%= contestant.weekly_points(current_season.weeks.find_by(week_number: n+1)) %></p></td>
              <% end %>
              <td class = "text-center"><p><%= contestant.season_points %></p></td>
              <% end %>
            </tr>
            <tr class="table-info">
              <td class = "text-left">Total</td>
              <% 10.times do |n| %>
              <% if current_season.weeks.pluck(:week_number).include?(n+1) %>
                  <td class = "text-center"><p><%= team.week_points(current_season.weeks.find_by(week_number: n+1)) %></p></td>
                <% else %>
                <td class = "text-center"><p>0</p></td>
                <% end %>
              <% end %>
              <td class = "text-center"><p><%= team.season_points %></p></td>
            </tr>

            </tbody>
          </table>
        </div>
      </div><br>
      <% end %>

  </div>
  <div class="tab-pane active" id="league-<%= @league.id %>-league" role="tabpanel">
    <div class="row">
      <div class="col-md-4">
        <div class="card">
          <div class="card-header">
            <h4>League Members</h4>
          </div>
          <div class="card-body">
            <% @league.teams.each do |team| %>
            <div class="team-members">

            <h5 class ="team-name">Team <%= team.name %></h5>
            <% team.users.each do |user| %>
            <p><%= user.name %></p>
            <% end %>
          </div>

            <% end %>

          </div>
        </div>
      </div>

    <div class="col-md-8">
      <div class="card">
        <div class="card-header">
          <h4 class = "text-center">League Overview</h4>
        </div><br><br>
        <div class="card-body">
    <table class="table table-responseive">
      <thead>
        <tr>
          <th class = "text-center">Team</th>
          <th class = "text-center">Points this Week</th>
          <th class = "text-center">Total Points</th>
        </tr>
      </thead>
      <tbody>
        <% @league.teams.each do |team| %>
        <tr>
          <td><%= team.name %></td>
          <td class = "text-center"><%= team.week_points(current_week) if current_week %></td>
          <td class = "text-center"><%= team.season_points %></td>
        </tr>
        <% end %>
      </tbody>
    </table>

  </div>
</div>
</div>
  </div>

  <% if current_season && current_season.drafted %>
  <div class="row">

  <div class="col-md-12">
    <div class="card">
      <div class="card-body">
        <h3 class="card-title"></h3>
        <div id="team-chart"></div>
      </div>
    </div>
  </div>
</div>
  <div class="row">

  <div class="col-md-6 mvp">
    <div class="card">
      <div class="card-header">
        <h4><i class="fa fa-star" aria-hidden="true"></i> Season MVP<i class="fa fa-star" aria-hidden="true"></i></h4>
      </div>
      <div class="card-body">
        <% if current_season.mvp %>
          <div class="md-circle-img-container">
            <img class = "img-responsive md-circular-cont-headshots" src="<%= current_season.mvp.headshot %> " alt="contestant headshot">
          </div>
          <h4><%= current_season.mvp.name %></h4>
          <h5><%= current_season.mvp.season_points %> Points</h5>
          <h5>Owned by team <%= @league.owner_of(current_season.mvp).name %></h5>
        <% else %>
          <br>
          <h2>No MVP yet!</h2>
        <% end %>
      </div>
    </div>
  </div>


    <div class="col-md-6">
      <div class="card">
        <div class="card-header">
          <h4><i class="fa fa-star" aria-hidden="true"></i> Highest Scoring Play this Season<i class="fa fa-star" aria-hidden="true"></i></h4>
        </div>
        <div class="card-body">
          <% if current_season.contestant_with_biggest_play %>
            <div class="md-circle-img-container">
              <img class = "img-responsive md-circular-cont-headshots" src="<%= current_season.contestant_with_biggest_play.headshot %> " alt="contestant headshot">
            </div>

            <h4><%= current_season.contestant_with_biggest_play.name %></h4>
            <h5><%= current_season.contestant_with_biggest_play.biggest_play.description %> for <%= current_season.contestant_with_biggest_play.biggest_play.point_value %> Points</h5>
            <h5>Owned by team <%= @league.owner_of(current_season.contestant_with_biggest_play).name %></h5>
          <% else %>
            <br>
            <h2>No plays yet!</h2>
          <% end %>
        </div>
      </div>
    </div>
  </div>

<% end %>
<h3 class = "text-center">Message Board</h3>
<div id="league-comments"></div>
      <div class="text-center">
        <form class="form-group">
          <input type="hidden" name="league_id" id = "league-id" value= "<%= @league.id %>" >
          <input type="text" name="message" placeholder="message" class="form-control" id="comment-message"><br>
          <button type="button" class="btn btn-primary" id="create-comment">Submit</button>
        </form>
    </div>
    </div>
  </div>
  </div>
</div>
</div>
</div>
<% end %>