config/routes.rb
Rails.application.routes.draw do
  get '/privacy_policy', to: 'privacy_policy#show'
  get '/auth/facebook', as: 'facebook_login'
  match '/auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  root 'users#show'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :users, only: [:show, :create]
  resources :leagues, only: [:show, :create] do
    resources :teams, only: [:index]
  end
  get '/start', to: 'start#show'
  resources :weeks, only: [:show]
  resources :contestants, only: [:show]
  get '/league_search', to: 'league_search#show'
  resources :team_members, only: [:create]
  resources :teams, only: [:create, :destroy] do
    resources :draft_picks, only: [:index]
    put '/draft_picks', to: 'draft_picks#update'
  end
  namespace :admin do
    resources :weekly_contestants, only: [:create]
    resources :team_contestants, only: [:create]
    resources :seasons, only: [:create, :index, :show, :update]
    resources :contestants, only: [:create]
    resources :weeks, only: [:create]
    resources :actions, only: [:create]
  end

  namespace :api do
    namespace :v1 do
      namespace :contestants do
        get ':id/weekly_points', to: 'points#show'
      end
      namespace :leagues do
        get ':id/team_points', to: 'team_points#index'
        get ':id/comments', to: 'comments#index'
        post ':id/comments', to: 'comments#create'
      end
    end
  end
end

app/models/season.rb
class Season < ApplicationRecord
  has_many :leagues, dependent: :destroy
  has_many :weeks, dependent: :destroy
  has_many :contestants, dependent: :destroy

  enum status: [:active, :retired]
  enum season_type: [:bachelor, :bachelorette]

  def mvp
    mvp = (contestants.sort_by {|cont| cont.season_points}).reverse.first
    (mvp if mvp.season_points > 0) || nil
  end

  def contestant_with_biggest_play
    contestants.joins(actions: :play).order("point_value DESC").first
  end


end

app/controllers/admin/seasons_controller.rb
class Admin::SeasonsController < Admin::BaseController
  def index
    @seasons = Season.all
  end

  def show
    @season = Season.find(params[:id])
  end

  def create
    @season = Season.new(season_params)
    if @season.save
      redirect_to admin_season_path(@season)
    else
      flash[:notice] = "Oops, there was a problem."
    end
  end

  def update
    season = Season.find(params[:id])
    new_status = season.status == "active" ? "retired" : "active"
    season.update(status: new_status)
    redirect_to admin_seasons_path
  end

  private

  def season_params
    params.require(:season).permit(:first_name, :last_name, :season_number, :season_type, :headshot, :draft_date)
  end
end

app/views/admin/seasons/index.html.erb
<div class="text-center">
  <h1 class = "page-header">All Seasons</h1><br><br>
</div>
<div class="text-center">
  <button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#create-season-modal">
    Add Season
  </button>
</div><br>

<div class="text-center">
  <% @seasons.each do |season| %>
    <h4><%= link_to "#{season.season_number} - #{season.first_name}", admin_season_path(season)  %>
      <%= link_to season.status == "active" ? "Deactivate" : "Activate", admin_season_path(season), method: :put, class: "btn btn-primary" %>
  </h4>
    <br>
  <% end %>
</div>

<!-- create season modal -->
<div class="modal fade" id="create-season-modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content text-center">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Add a Season</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= form_for(:season, url: admin_seasons_path) do |f| %>
          <div class="form-group row">
            <%= f.label :first_name, "First Name", class: "col-md-3 col-form-label" %>
            <%= f.text_field :first_name, class: "form-control col-md-8" %>
          </div>
          <div class="form-group row">
            <%= f.label :last_name, "Last Name", class: "col-md-3 col-form-label" %>
            <%= f.text_field :last_name, class: "form-control col-md-8" %>
          </div>
          <div class="form-group row">
            <%= f.label :season_number, "Season #", class: "col-md-3 col-form-label" %>
            <%= f.text_field :season_number, class: "form-control col-md-8" %>
          </div>
          <div class="form-group row">
            <%= f.label :season_type, "Season Type", class: "col-md-3 col-form-label" %>
          <div class="col-md-8">
            <%= f.radio_button :season_type, 'bachelor', :checked => true %>
            <%= label :season_type_bachelor, 'Bachelor' %>
            <%= f.radio_button :season_type, 'bachelorette' %>
            <%= label :season_type_bachelorette, 'Bachelorette' %>
          </div>
          </div>
          <div class="form-group row">
            <%= f.label :headshot, "Headshot", class: "col-md-3 col-form-label" %>
            <%= f.text_field :headshot, class: "form-control col-md-8" %>
          </div>
          <div class="form-group row">
            <%= f.label :draft_date, "Draft Date", class: "col-md-3 col-form-label" %>
            <%= f.date_field :draft_date, class: "form-control col-md-8" %>
          </div>
          <br><br>
          <%= f.submit 'Create', :class =>"btn btn-primary"%>
        <% end %>
        <br>
      </div>
    </div>
  </div>
</div>

app/views/admin/seasons/show.html.erb
<div class="text-center">
  <h1 class = "page-header"><%= "#{@season.first_name} #{@season.last_name}" %></h1>
</div>
<div class="card">
  <div class="card-header text-center">
    <h4>Basic Info</h4>
  </div>
  <div class="card-body">
    <div class="row">
      <div class="col-md-6">
        <p>Season Number: <%= @season.season_number %></p>
        <p>Season Type: <%= @season.season_type %></p>
        <p>Status: <%= @season.status %></p>
        <p>Draft Date: <%= @season.draft_date %></p>
        <p>Drafted: <%= @season.drafted %></p>
      </div>
      <div class="col-md-6">
        <img class = "circular-headshots" src="<%= @season.headshot %>" alt="bachelor/bachelorette headshot">
      </div>
    </div>
  </div>
</div><br>


  <div class="row">
    <div class="col-md-6">
      <div class="card">
        <div class="card-header text-center">
          <h4>Contestants (<%= @season.contestants.count %>)</h4>
        </div><br>
        <button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#create-contestant-modal">
          Add Contestant
        </button>
        <div class="card-body row">
          <% @season.contestants.each do |contestant| %>
          <div class="col-md-6">

          <div class="circle-img-container">

            <span class = "text-center"><img class = "circular-cont-headshots" src="<%= contestant.headshot %>" alt="contestant-headshot"></span>
          </div>
            <%= contestant.name %><br>
          </div>
          <% end %>
        </div>
      </div>
    </div>
    <div class="col-md-6">
      <div class="card">
        <div class="card-header text-center">
          <h4>Schedule</h4>
        </div><br>
        <button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#create-week-modal">
          Add Episode
        </button>
        <div class="card-body">

          <table class="table">
            <thead>
              <tr>
                <th scope="col">Episode #</th>
                <td scope="col">Date</td>
              </tr>
            </thead>
            <tbody>
              <% @season.weeks.order(:date).each do |week| %>
              <tr>
                <th><%= week.week_number %></th>
                <td><%= week.date %></td>
              </tr>
              <% end %>
            </tbody>
          </table>
        </div>
    </div>

    </div>
  </div><br>
  <div class="row text-center">
    <div class=" col-md-3">
      <% if current_season && current_season.drafted %>
        <%= link_to "Initiate Draft", '#',  class: "btn btn-primary btn-lg btn-disabled" %>
      <% else %>
        <%= link_to "Initiate Draft", admin_team_contestants_path, method: :post, class: "btn btn-primary btn-lg" %>
      <% end %><br><br>
    </div>
    <div class=" col-md-3">
      <% if current_season.weeks.find_by(week_number: 1) %>
        <%= link_to "Add Contestants to First Episode", admin_weekly_contestants_path(season_id: @season.id, week_id: current_season.weeks.find_by(week_number: 1).id, contestant_ids: current_season.contestants.pluck(:id)), method: :post, class: "btn btn-primary btn-lg" %>
      <% end %>
    <br><br>
    </div>
  </div>


  <!-- create contestant modal -->
  <div class="modal fade" id="create-contestant-modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content text-center">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Add a Contestant</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <%= form_for(:contestant, url: admin_contestants_path) do |f| %>
            <%= f.hidden_field :season_id, :value => @season.id %>
            <div class="form-group row">
              <%= f.label :name, "Name", class: "col-md-3 col-form-label" %>
              <%= f.text_field :name, class: "form-control col-md-8" %>
            </div>
            <div class="form-group row">
              <%= f.label :headshot, "Headshot", class: "col-md-3 col-form-label" %>
              <%= f.text_field :headshot, class: "form-control col-md-8" %>
            </div>
            <div class="form-group row">
              <%= f.label :twitter_handle, "Twitter", class: "col-md-3 col-form-label" %>
              <%= f.text_field :twitter_handle, class: "form-control col-md-8" %>
            </div>
            <div class="form-group row">
              <%= f.label :age, "Age", class: "col-md-3 col-form-label" %>
              <%= f.text_field :age, class: "form-control col-md-8" %>
            </div>
            <div class="form-group row">
              <%= f.label :hometown, "Hometown", class: "col-md-3 col-form-label" %>
              <%= f.text_field :hometown, class: "form-control col-md-8" %>
            </div>
            <div class="form-group row">
              <%= f.label :occupation, "Occupation", class: "col-md-3 col-form-label" %>
              <%= f.text_field :occupation, class: "form-control col-md-8" %>
            </div>
            <div class="form-group row">
              <%= f.label :bio, "Bio", class: "col-md-3 col-form-label" %>
              <%= f.text_area :bio, class: "form-control col-md-8", rows:6 %>
            </div>
            <br><br>
            <%= f.submit 'Create', :class =>"btn btn-primary"%>
          <% end %>
          <br>
        </div>
      </div>
    </div>
  </div>

  <!-- create week modal -->
  <div class="modal fade" id="create-week-modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content text-center">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Add an Episode</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <%= form_for(:week, url: admin_weeks_path) do |f| %>
            <%= f.hidden_field :season_id, :value => @season.id %>
            <div class="form-group row">
              <%= f.label :week_number, "Episode Number", class: "col-md-3 col-form-label" %>
              <%= f.text_field :week_number, class: "form-control col-md-8" %>
            </div>
            <div class="form-group row">
              <%= f.label :date, "Date", class: "col-md-3 col-form-label" %>
              <%= f.date_field :date, class: "form-control col-md-8" %>
            </div>
            <br><br>
            <%= f.submit 'Create', :class =>"btn btn-primary"%>
          <% end %>
          <br>
        </div>
      </div>
    </div>
  </div>