config/routes.rb
Rails.application.routes.draw do
  get '/privacy_policy', to: 'privacy_policy#show'
  get '/auth/facebook', as: 'facebook_login'
  match '/auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  root 'users#show'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :users, only: [:show, :create]
  resources :leagues, only: [:show, :create] do
    resources :teams, only: [:index]
  end
  get '/start', to: 'start#show'
  resources :weeks, only: [:show]
  resources :contestants, only: [:show]
  get '/league_search', to: 'league_search#show'
  resources :team_members, only: [:create]
  resources :teams, only: [:create, :destroy] do
    resources :draft_picks, only: [:index]
    put '/draft_picks', to: 'draft_picks#update'
  end
  namespace :admin do
    resources :weekly_contestants, only: [:create]
    resources :team_contestants, only: [:create]
    resources :seasons, only: [:create, :index, :show, :update]
    resources :contestants, only: [:create]
    resources :weeks, only: [:create]
    resources :actions, only: [:create]
  end

  namespace :api do
    namespace :v1 do
      namespace :contestants do
        get ':id/weekly_points', to: 'points#show'
      end
      namespace :leagues do
        get ':id/team_points', to: 'team_points#index'
        get ':id/comments', to: 'comments#index'
        post ':id/comments', to: 'comments#create'
      end
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # has_secure_password
  has_many :team_members
  has_many :teams, through: :team_members
  has_many :comments
  has_many :identities

  validates :email, :presence => true

  enum role: %w(default admin)

  def self.create_with_omniauth(auth, identity)
    puts "creating new user #{auth[:info][:name]} (#{auth[:info][:email]}) with omniauth"
    user = User.create!(name: auth[:info][:name],
                      email: auth[:info][:email])
    puts "user #{auth[:info][:name]} (#{auth[:info][:email]}) created!" if user
    puts "user #{auth[:info][:name]} (#{auth[:info][:email]}) creation failed" unless user
    identity.update(user_id: user.id)
  end

  def active_leagues
    League.joins(:season, teams: :team_members)
          .where("team_members.user_id = ?", id)
          .where("seasons.status = ?", 0)
  end

  def leagues
    League.joins(teams: :team_members)
          .where("team_members.user_id = ?", id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_login, only: [:show]

  def show
    redirect_to start_path if current_user.active_leagues.empty?
    redirect_to league_path(current_user.active_leagues.first) unless current_user.active_leagues.empty?
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "Your account has been created!"
      redirect_to @user
    else
      @user.errors.full_messages.each do |error|
        flash[:notice] = error
      end
      redirect_to new_user_path
    end
  end

  private

  def find_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/views/users/_user_profile_navbar.html.erb
<div class = "page-header">


    <span class = "in-line"><h2>League <%= @league.name %> <%= link_to "League Details", league_teams_path(@league), class: "btn btn-primary btn-sm" %></span></h2>

<% if @league.team_of_user(current_user) %>
  <div class="float-right">
    <span class = "in-line"><h2>Team <%= @league.team_of_user(current_user).name %></span></h2>
  </div>
<% end %>
</div>

app/views/users/new.html.erb
<div class="row">
  <div class="col-md-3">

  </div>
<div class="col col-md-6">
  <br><h1 class="text-center">Sign Up!</h1><br>

<%= form_for @user do |f| %>
<div class="form-group row">
  <%= f.label :name, class: "col-md-4 col-form-label" %>
  <%= f.text_field :name, class: "form-control col-md-6" %>
</div>
<div class="form-group row">
  <%= f.label :email, class: "col-md-4 col-form-label" %>
  <%= f.text_field :email, class: "form-control col-md-6" %>
</div>
<div class="form-group row">
  <%= f.label :password, class: "col-md-4 col-form-label" %>
  <%= f.password_field :password, class: "form-control col-md-6" %>
</div>
<div class="form-group row">
  <%= f.label :password_confirmation, class: "col-md-4 col-form-label" %>
  <%= f.password_field :password_confirmation, class: "form-control col-md-6" %>
</div>
<div class="text-center">

  <%= f.submit "Sign Up!", class: "btn btn-primary" %>
</div>

<% end %>
</div>
<div class="col-md-3">

</div>
</div>