config/routes.rb
Rails.application.routes.draw do
  get '/privacy_policy', to: 'privacy_policy#show'
  get '/auth/facebook', as: 'facebook_login'
  match '/auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  root 'users#show'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :users, only: [:show, :create]
  resources :leagues, only: [:show, :create] do
    resources :teams, only: [:index]
  end
  get '/start', to: 'start#show'
  resources :weeks, only: [:show]
  resources :contestants, only: [:show]
  get '/league_search', to: 'league_search#show'
  resources :team_members, only: [:create]
  resources :teams, only: [:create, :destroy] do
    resources :draft_picks, only: [:index]
    put '/draft_picks', to: 'draft_picks#update'
  end
  namespace :admin do
    resources :weekly_contestants, only: [:create]
    resources :team_contestants, only: [:create]
    resources :seasons, only: [:create, :index, :show, :update]
    resources :contestants, only: [:create]
    resources :weeks, only: [:create]
    resources :actions, only: [:create]
  end

  namespace :api do
    namespace :v1 do
      namespace :contestants do
        get ':id/weekly_points', to: 'points#show'
      end
      namespace :leagues do
        get ':id/team_points', to: 'team_points#index'
        get ':id/comments', to: 'comments#index'
        post ':id/comments', to: 'comments#create'
      end
    end
  end
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg">
  <div class="container">
  <a class="navbar-brand" href="/">Not Here to Make Friends</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item dropdown">
  <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Your Leagues</a>
  <div class="dropdown-menu">
    <% current_user.active_leagues.each do |league| %>
      <p><%= link_to league.name, league_path(league), class: "dropdown-item" %></p>
    <% end %>
    <% if current_season && !current_season.drafted %>
      <p><%= link_to "+ Create or Join", start_path, class: "dropdown-item green-text" %></p>
    <% end %>
  </div>
</li>
<% if current_week %>
      <li class="nav-item">
        <%= link_to "This Week", (week_path(current_week) if current_week) || "#", class: "nav-link" %>
      </li>

<% end %>
<li class="nav-item dropdown">
  <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Contestants</a>
  <div class="dropdown-menu">
    <% current_season.contestants.each do |contestant| %>
      <p><%= link_to contestant.name, contestant_path(contestant), class: "dropdown-item" %></p>
    <% end %>
  </div>
</li>

      <% if current_admin? %>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Admin Tasks</a>
        <div class="dropdown-menu">
          <p><%= link_to "Manage Seasons", admin_seasons_path, class: "dropdown-item" %></p>
          <p><%= link_to "Enter Results", '#', class: "dropdown-item" %></p>
        </div>
      </li>
      <% end %>
      <li class="nav-item">
        <%= link_to "Log Out", logout_path, method: :delete, class: "nav-link" %>
      </li>
    </ul>
  </div>
</div>
</nav>
<div class="container">

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NotHereToMakeFriends</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_include_tag('jquery.circliful.min') %>
    <%= stylesheet_link_tag('jquery.circliful') %>

    <script src="https://code.highcharts.com/highcharts.js"></script>
  </head>
  <% if current_page?(login_path) && !current_user %>
    <body class="splash" id = "bootstrap-override">
  <% else %>
    <body id = "bootstrap-override">
  <% end %>
    <% if current_user %>
      <%= render partial: "layouts/navbar" %>
    <% end %>
    <% flash.each do |name, msg| %>
      <%= content_tag :div, msg, :id => "flash_#{name}", class: "alert alert-primary text-center" %>
    <% end %>
    <main>
      <%= yield %>
    </main>
    <footer>
    </footer>
  </body>

</html>